name: Build Atroc-0625/warp-plus-cloudflare

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "00 03 * * *"
  watch:
    types: [started]
    
jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v2.3.4
                          
            - name: Step 2 - Build warp-plus-cloudflare
              run: |
                  sudo cat wp-plus.py
