name: Build Atroc-0625/warp-plus-cloudflare

on:
  push:
    branches: [ master ]
    
  watch:
    types: [started]
    
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v2.3.4
                          
            - name: Step 2 - Build warp-plus-cloudflare
              run: |
                  sudo python3 --version
                  sudo python3 wp-plus.py
